### PR TITLE
Some changes re discussions below

### PR DESCRIPTION
**Pull request by nabils**
Hi Davy,

Had a go at the changes regarding the two discussions below? Let me know what you think. 

http://groups.google.com/group/agatha-rrsl/browse_thread/thread/afa381e8d0c789b3
http://groups.google.com/group/agatha-rrsl/browse_thread/thread/5cff6ddf3979abed

Regards,
Nabil

### CODE REVIEW

**Comment by nabils** [comment]
I am a beginner at Git so not sure why the diffs are not right on some of the files!! If you could let me know please I'll get it fixed. Thanks

**Comment by davybrion** [comment]
i think the 'incorrect' diffs are tabs vs spaces thing

The changes look good, though i'd rather avoid adding the ExceptionType enum property to ExceptionInfo (and setting it in the RequestProcessor). For starters, this patch would end up in Agatha 1.3.1 and i'd like to avoid changes in types that go over the wire within the same major.minor version.  I'm also not sure what the impact on Silverlight code would be... 

So if you remove the changes to ExceptionInfo, i'll merge :)
we could add the ExceptionType enum property to ExceptionInfo in 1.4

**Comment by bartdeleye** [comment]
There are 2 copy-paste errors in RequestHandlerBasedConventions at line 69 and 71. 
Can you add a test to the RequestHandlerBasedConventionsSpecs.cs for the response-request mapping?

**Comment by nabils** [comment]
That's fine with me Davy. Any idea when 1.3.1 will be available?

Bart,

New commit above with those issues fixed. Thanks for spotting my lazy bugs :)

**Comment by davybrion** [comment]
i'm gonna try to get 1.3.1 out the door in the upcoming weekend

if you remove the ExceptionType property from the ExceptionInfo class, i'll merge this into it... if not, i'd rather add this in the 1.4 release

**Comment by nabils** [comment]
Ok i'll remove exceptiontype within the next few days.

Best Regards
Nabil Shuhaiber

On 17 Oct 2011, at 21:11, Davy Brion
reply@reply.github.com
wrote:

**Comment by nabils** [comment]
Done. Hope it is ok now.

**Pull request merged**
