### PR TITLE
Added CLSCompliantAttribute, commited CommonAssemblyInfo to make possible to compile project from VS without running rake

### PR DESCRIPTION
**Pull request by whut**
To small changes that you might be interested in:

1) Added CLSCompliantAttribute - In my project we have CLSCompliantAttribute(true). If Agatha is not compiled also with this attribute it causes complier warning. Other OS frameworks like NHibernate also have this attribute set.

2) Commited CommonAssemblyInfo.cs - to make possible to just compile solution from VS without running rake

### CODE REVIEW

**Comment by davybrion** [comment]
according to the albacore documentation for the assemblyinfo task that we use (https://github.com/derickbailey/Albacore/wiki/assemblyinfotask), we could just add something like this to our rakefile:

asm.custom_attributes :CLSCompliant => true

i'm not opposed to adding the CommonAssemblyInfo file, but it should come with a clear warning that it is a generated file and that the proper way to change it is through the Rakefile

**Comment by whut** [comment]
I tried to add CLSCompliant trough rake file, but not all projects are CLS compliant (Tests, Agatha.Spring and and one other),

Right, I will look at albacore later today to find a way to add comment to assemblyinfo.

**Comment by bartdeleye** [comment]
1) You can also add a SpecificAssemblyInfo.cs to a subset of the projects if not all assemblies need to be CLSCompliant

2) I would not commit generated files. You only have to run the build script once before you can compile in VS as much as you want.

**Comment by whut** [comment]
1) That's what I did (?)

2) Right, committing generated files is Bad Thing, but in this specific case IMO it's not harmful at all, and allows one-shot developers (like me:) ) to quickly hack something in agatha sources without going into ruby stuff

**Comment by davybrion** [comment]
thx!

**Pull request merged**
