### PR TITLE
Initial try at portable class library support

### PR DESCRIPTION
**Pull request by nabils**
As discussed in http://groups.google.com/group/agatha-rrsl/browse_thread/thread/d6e83f08f0885ba4

### CODE REVIEW

**Comment by davybrion** [comment]
Could you change the commit so it uses spaces instead of tabs in the files? it's pretty much impossible to spot changes in some files now... RequestProcessor and a lot of .csproj files are displayed as pretty much changed in their entirety so I'm guessing those files are using tabs iso spaces now.

**Comment by nabils** [comment]
Where do I do this so that it can convert automatically? In visual studio
or git? And how? Sorry am a beginner with git. I have tried to google the
issue but not found anything.

On 26 February 2012 19:36, Davy Brion <
reply@reply.github.com

> wrote:
> 
> Could you change the commit so it uses spaces instead of tabs in the
> files? it's pretty much impossible to spot changes in some files now...
> RequestProcessor and a lot of .csproj files are displayed as pretty much
> changed in their entirety so I'm guessing those files are using tabs iso
> spaces now.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/davybrion/Agatha/pull/20#issuecomment-4183808

## 

Best Regards,
Nabil Shuhaiber

**Comment by davybrion** [comment]
It's not a git issue... I think your Visual Studio settings for c# and xml are set to use tabs instead of inserting spaces

**Comment by nabils** [comment]
Yes it probably is. I can fix that. Problem is how do I fix the commit once I have made that change. I would need to recreate my fork on github and reapply all the changes! That can't be the only way?

**Comment by davybrion** [comment]
no you can do that in a separate commit, and then add that commit to this pull request

**Comment by davybrion** [comment]
also, the commits where you added the extra files to the portable library (as you mentioned on the mailinglist) can be added to this pull request as well

**Comment by nabils** [comment]
Ok will do that this evening.

Best Regards
Nabil Shuhaiber

On 26 Feb 2012, at 22:00, Davy Brion
reply@reply.github.com
wrote:

**Comment by nabils** [comment]
Going to send over a new pull request. It was actually not related to tab/spaces but core.autocrlf=true setting in git.

**Pull request closed without merging**
