### PR TITLE
Ioc update

### PR DESCRIPTION
**Pull request by michaelaird**
I've updated all the IOC containers to the latest versions and updated the related nuspec files.

### CODE REVIEW

**Comment by michaelaird** [comment]
The unit tests all pass on my machine but it would be good for other folks to run them as well.

**Comment by davybrion** [comment]
thx for this, and sorry for the long delay

**Comment by michaelaird** [comment]
No worries. Any chance of publishing an updated NuGet package with this?

**Comment by davybrion** [comment]
not sure... i don't think there are enough changes to warrant a new package, yet i don't plan on making many changes to this project anymore.

It feels kinda wrong to release a new package solely because the dependencies have been updated... thoughts?

**Comment by BennyM** [comment]
It won't work with a simple redirect since there are breaking changes, so a new package would be welcome.

**Comment by michaelaird** [comment]
Agreed. What about making the updated package 1.3.1 to indicate that the changes are very minor?

**Comment by davybrion** [comment]
just pushed 1.3.1 versions for packages where the IOC container was updated

**Pull request merged**
