### PR TITLE
Portable class library support

### PR DESCRIPTION
**Pull request by nabils**
Sorry this a big mess now. The last commit is the correct one.

### CODE REVIEW

**Comment by davybrion** [comment]
this looks good

i'm gonna merge it this weekend

**Comment by nabils** [comment]
Great thanks

Nabil

On 1 Mar 2012, at 20:09, Davy Brion
reply@reply.github.com
wrote:

**Comment by davybrion** [comment]
apparently this requires the installation of the Portable Library power tool for Visual Studio... this is a developer dependency I'm unwilling to introduce, especially since it would be required for the core Request and Response types.

So I'm going to have to turn down this pull request... sorry.

**Comment by nabils** [comment]
Ok no problem. Thanks.

On 3 Mar 2012, at 14:21, Davy Brion
reply@reply.github.com
wrote:

**Comment by michaelaird** [comment]
Now that these things are built into the last few versions of Visual Studio, I took another crack at it this weekend. If anyone is interested, it's in my branch here:

https://github.com/michaelaird/Agatha/tree/PCL

**Pull request closed without merging**
